### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by GirafiStudios** [Motschen/WaddlesFabricRevived#1]
Hey Motschen.

Saw you forked Waddles the other day, and noticed you have worked on getting it to work on Fabric 1.15.
I was wondering what your plans with it was?

**Comment by Motschen** [comment]
I want to finish this port and then send it to you to upload on curseforge.

**Comment by GirafiStudios** [comment]
Sounds good, appreciate it 👍

**Comment by GirafiStudios** [comment]
I've created a new 1.15-Fabric branch you can PR against, when you get that far :)
